// SPDX-License-Identifier: MIT

/**
 * Yuigram — an independent TypeScript framework for the Telegram Bot API
 * and MTProto.
 *
 * This package is the façade users install. It re-exports the public surface
 * and contains almost no logic of its own: one import path, one thing to learn,
 * and no decision to make about which internal package a symbol lives in.
 *
 * ```ts
 * import { Bot } from 'yuigram'
 *
 * const bot = Bot.fromToken(process.env.BOT_TOKEN!)
 *
 * bot.onCommand('start', (message) => message.reply('Hello.'))
 *
 * await bot.poll()
 * ```
 *
 * **What is here:** the Bot API subsystem — clients, polling, webhooks,
 * routing, sessions, storage, files, errors and the testing harness — and the
 * MTProto subsystem's account client, with the message, chat, dialog and member
 * operations built on its generated surface. And `App`, which holds several
 * clients of either kind at once:
 *
 * ```ts
 * import { App, Account, Bot } from 'yuigram'
 *
 * const app = new App()
 *
 * app.add(Bot.fromToken(process.env.BOT_TOKEN!))
 * app.add(new Account({ name: 'me', ...credentials }))
 *
 * await app.start()
 * ```
 *
 * Neither subsystem imports the other — they meet here, and nowhere else.
 *
 * There is no single `Context` type to name, because registration decides what
 * a handler receives: `onCommand` hands you a message whose `text` is a
 * `string`, `onMessage` one whose `text` may be absent, and `on('poll_answer')`
 * something with neither. `Context` here is core's transport-agnostic base,
 * which is what generic middleware is written against.
 *
 * Extensions ride on a type parameter rather than a globally merged interface,
 * so an application names what plugins add, once:
 *
 * ```ts
 * const bot = Bot.fromToken<SessionFlavor<Cart>>(token)
 * ```
 *
 * Two bots in one program can then hold different state, which a merged
 * interface cannot express.
 *
 * **What is not:** secret chats, and whatever else `docs/roadmap.md` lists as
 * planned rather than shipped. Nothing exported here is a placeholder.
 */

// The MTProto subsystem is requested first, and the order is load-bearing. A
// bundler such as esbuild wraps its shared modules for the parts it loads
// lazily, and the core those modules initialize has to be in place before the
// Bot API's modules extend its errors. Bundled the other way round, a program
// throws on load — `tools/bench` portability catches it.
import { TL_LAYER } from '@yuigram/mtproto'

export * from '@yuigram/bot-api'

// After the line above, so it adds nothing to the order modules load in.
import { BOT_API_VERSION } from '@yuigram/bot-api'

/**
 * The scheduler this façade exposes is the Bot API one.
 *
 * Both packages carry a `createScheduler`: the core package's is generic over
 * whatever a caller wants ordered, and the Bot API's supplies the chat as that
 * key. A bot reaching for one wants the second, so the ambiguity is resolved
 * here rather than left to whichever export happens to win.
 */
export { createScheduler } from '@yuigram/bot-api'
export * from '@yuigram/core'
/**
 * The MTProto subsystem, named rather than starred.
 *
 * The other two are re-exported wholesale because everything they publish is
 * meant for a user. This one is listed because two of its exports are not:
 * `PACKAGE_NAME` is a diagnostic that means nothing from here, and its
 * `NormalizedUpdate` shares a name with the Bot API's while describing a
 * different shape — starring both would leave neither reachable, silently. A
 * caller reads those fields off {@link MtprotoContext}, which is what a handler
 * is actually given.
 */
export {
  Account,
  type AccountContext,
  type AccountFilterContext,
  type AccountOptions,
  AccountRouter,
  type AddOptions,
  type AdminRights,
  type AlbumItem,
  type AlbumOptions,
  type AllStoriesFilter,
  type AllStoriesOptions,
  type AllStoriesPage,
  addContact,
  allStoriesPage,
  answerCallback,
  answerInlineQuery,
  answerPrecheckout,
  answerShipping,
  areaFor,
  type BoostChance,
  type BoostFilter,
  type BoostPage,
  type BoostWalkOptions,
  type BootstrapAddress,
  type BotInfo,
  type BotInfoTarget,
  type BoundApi,
  type BoundCalls,
  type BusinessIntro,
  type ButtonAnswer,
  block,
  boostsPage,
  bootstrapAt,
  type CallbackAnswer,
  type CallDefaults,
  type CallEndReason,
  type ChatEventFilter,
  type ChatEventOptions,
  type ChatEventPage,
  ChatEventView,
  type ChatForm,
  type ChatKind,
  type ChatlistPreview,
  type Chatting,
  ChatView,
  type CollectibleInfo,
  type CollectibleKind,
  type CommandInfo,
  type CommandScope,
  type CommandsTarget,
  type CommunityLinkRequestView,
  type CommunityPeerView,
  type ConnectionRoute,
  type CopyOptions,
  CursorError,
  callbackButton,
  cancelRecoveryEmail,
  chatEventsPage,
  checkRecoveryCode,
  commonChats,
  confirmRecoveryEmail,
  type DcAddress,
  type DcConfiguration,
  type DialogFilter,
  type DialogForm,
  type DialogOptions,
  type DialogPage,
  type DialogsOffset,
  DialogView,
  type Discussion,
  type DocumentedErrorPattern,
  type DocumentedErrorText,
  type DownloadMode,
  type DownloadOutcome,
  type DownloadRequest,
  type DownloadSink,
  type DraftOptions,
  decideJoinRequest,
  deleteContacts,
  deleteMessages,
  deleteProfilePhotos,
  detectMimeType,
  dialogsPage,
  documentFile,
  documentMedia,
  type EditEphemeralOptions,
  type EditOptions,
  type EphemeralButtonAnswer,
  type EphemeralContent,
  type EphemeralMessageView,
  type EphemeralTarget,
  editMessage,
  editProfile,
  FileIdError,
  type FileIdentity,
  type FileKind,
  type FileWhere,
  type Folder,
  type FolderQuery,
  type FormattedText,
  type ForumSettings,
  ForumTopicView,
  type ForwardOptions,
  type FullChat,
  type FullProfile,
  fileFor,
  fileIdOfDocument,
  fileIdOfPhoto,
  fileIdOfThumbnail,
  fileNameOf,
  findByPhone,
  forumTopicsPage,
  forwardMessages,
  fromHtml,
  fromMarkdown,
  type GameDetails,
  type GameScore,
  type GiftFilter,
  type GiftNote,
  type GiftOffer,
  type GiftPage,
  type GiftRef,
  type GiftVerdict,
  type GiftWalkOptions,
  type GlobalSearchFilter,
  type GlobalSearchOptions,
  getMessages,
  type HistoryFilter,
  type HistoryOptions,
  type HistoryRemoval,
  type HtmlParseOptions,
  type HtmlReader,
  type HtmlWriteOptions,
  hashtagPage,
  historyPage,
  type ImporterFilter,
  type ImporterWalkOptions,
  type ImportOutcome,
  type InlineAnswer,
  type InlineEditOptions,
  type InviteFilter,
  InviteImporterView,
  type InviteLinkEdit,
  type InviteLinkPage,
  InviteLinkView,
  type InviteMemberPage,
  type InvitePreview,
  type InviteWalkOptions,
  importContacts,
  inferMimeType,
  inlineKeyboard,
  inputChannel,
  inputDocumentOf,
  inputPeer,
  inputPeerFromMessage,
  inputPhotoOf,
  inviteLinksPage,
  inviteMembersPage,
  isProbablyText,
  isRpcError,
  joinText,
  knows,
  type LinkMessage,
  type LinkRequestAction,
  type LinkRequestsPage,
  type LocationDetails,
  type LoginTokenState,
  locationOf,
  looksLikeFileId,
  type MarkdownParseOptions,
  type MarkdownReader,
  type Markup,
  type MarkupMode,
  type MaskPoint,
  type MediaDownloadOptions,
  type MediaKind,
  MediaView,
  type MemberFilter,
  type MemberOptions,
  type MemberPage,
  type MemberStanding,
  MemberView,
  type MenuButtonSetting,
  type MessageBody,
  type MessageEffects,
  type MessageForm,
  type MessagePage,
  MessageView,
  MigrationError,
  type MigrationKind,
  type MtprotoApi,
  type MtprotoContext,
  type MtprotoEventKind,
  type MusicPage,
  type MySetsPage,
  mediaOf,
  membersPage,
  messageTtl,
  mimeTypeOfName,
  myUsername,
  type NewChat,
  type NewCommunity,
  type NewContact,
  type NewFolder,
  type NewGift,
  type NewInviteLink,
  type NewPassword,
  type NewSticker,
  type NewStickerSet,
  type NewStory,
  type NewTopic,
  type NodeReadable,
  type NotAdded,
  nextDialogs,
  normalizePhone,
  type OpenHours,
  type PageOf,
  type PageOptions,
  type PageTotal,
  type Paging,
  type PaidReactionOptions,
  type ParticipantChats,
  type PasswordStatus,
  type PeerBearing,
  type PeeredPage,
  PeerIndex,
  type PeerKind,
  type PeerRecord,
  type PeerRef,
  type PeerStore,
  PeerStoriesView,
  type PeerView,
  type PhoneContact,
  type PhotoPage,
  type PhotoSource,
  type PhotoThumbnail,
  type PollAnswerDetails,
  type PollDetails,
  type PollState,
  type PostPage,
  type PostSearchFilter,
  type PostSearchOptions,
  type PreparedMessage,
  type PreparedTarget,
  type ProfileEdit,
  type ProfileStoriesPage,
  type Profiling,
  passwordStatus,
  peerOfInput,
  peerSettings,
  photoFile,
  photoMedia,
  pinMessage,
  postSearchPage,
  profilePhoto,
  profilePhotosPage,
  profileStoriesPage,
  type QrOptions,
  type Quote,
  quoteOf,
  type ReactionFilter,
  type ReactionIdentity,
  type ReactionInput,
  type ReactionKind,
  type ReactionPage,
  ReactionView,
  type ReactionWalkOptions,
  type ResaleAttributes,
  type ResalePage,
  type ResaleQuery,
  type Restrictions,
  type RichContent,
  type RichFile,
  RpcError,
  type RpcErrorPattern,
  type RpcErrorText,
  type RpcErrorTextOf,
  react,
  reactionsPage,
  readAction,
  readBlocked,
  readChat,
  readContacts,
  readDialog,
  readFileId,
  readForumTopic,
  readGame,
  readHistory,
  readLocation,
  readMedia,
  readMember,
  readMessage,
  readPeerReference,
  readPeers,
  readPoll,
  readPresence,
  readProfile,
  readReaction,
  readSession,
  readSticker,
  readStickerSet,
  readStory,
  readTodo,
  readUser,
  readUsers,
  readWebPage,
  removePassword,
  requestPasswordRecovery,
  resendRecoveryEmail,
  resolveMany,
  type ScoreOptions,
  type SearchFilter,
  type SearchOptions,
  type Securing,
  type SendEphemeralOptions,
  type Sending,
  type SendOptions,
  type SentMessage,
  type SentScheduled,
  type ServerRsaKey,
  type ServiceAction,
  type ServiceActionKind,
  type ServiceActionOf,
  type SessionAddress,
  type SessionFormat,
  type SessionImportOptions,
  type SharedPeer,
  type ShippingAnswer,
  type SignInState,
  type SimilarChannelsPage,
  type StarsFilter,
  type StarsPage,
  type StarsPrice,
  type StarsWalkOptions,
  type StickerDetails,
  type StickerItem,
  type StickerRef,
  type StickerSetContents,
  type StickerSetKind,
  type StickerSetRef,
  type StickerSetValue,
  StickerSetView,
  StorageOwnershipError,
  type StoryAllowance,
  type StoryCaption,
  type StoryEdit,
  type StoryFilter,
  type StoryForm,
  type StoryReaction,
  StoryView,
  type StoryViewerPage,
  StoryViewerView,
  type StoryWalkOptions,
  type StreamingDraft,
  type StreamOptions,
  sameMessage,
  sameTopic,
  savedGiftsPage,
  savedMusic,
  savedMusicPage,
  saveMusic,
  searchGlobalPage,
  searchPage,
  sendMedia,
  sendText,
  sentMessage,
  serverKeysFromPem,
  serverRsaKey,
  setBirthday,
  setCloseFriends,
  setContactNote,
  setEmojiStatus,
  setMessageTtl,
  setOnline,
  setPassword,
  setProfilePhoto,
  setTyping,
  setUsername,
  similarChannelsPage,
  starsTransactionsPage,
  storyViewersPage,
  type TakeoutScope,
  type TakeoutSession,
  type TextDraft,
  type Thumbnail,
  type ThumbnailAvailability,
  type TlValue,
  type TodoDetails,
  type TodoItemDetails,
  type TopicEdit,
  type TopicFilter,
  type TopicIcon,
  type TopicPage,
  type TopicRef,
  type TopicWalkOptions,
  type TotalPrecision,
  type TransferredSession,
  type TranslateOptions,
  type Translation,
  thumbnail,
  thumbnailFile,
  thumbnails,
  toHtml,
  toInputChannel,
  toInputUser,
  toMarkdown,
  type UpgradeOptions,
  type UploadedDocumentOptions,
  type UploadedFile,
  type UploadRequest,
  type UploadSource,
  type UserPresence,
  UserView,
  unblock,
  uniqueFileId,
  uploadedDocument,
  uploadedPhoto,
  urlButton,
  type ViewerFilter,
  type ViewerKind,
  type ViewerWalkOptions,
  type WalkOptions,
  type WebPageDetails,
  type WebView,
  type WebViewRequest,
  type WebViewSource,
  type WorkHours,
  walkAllStories,
  walkBoosts,
  walkChatEvents,
  walkDialogs,
  walkForumTopics,
  walkGlobalSearch,
  walkHashtagSearch,
  walkHistory,
  walkInviteLinks,
  walkInviteMembers,
  walkMembers,
  walkPostSearch,
  walkProfilePhotos,
  walkProfileStories,
  walkReactions,
  walkSavedGifts,
  walkSavedMusic,
  walkSearch,
  walkStarsTransactions,
  walkStoryViewers,
  webLocationOf,
  whoAmI,
  writeFileId,
  writeSession,
} from '@yuigram/mtproto'

/**
 * Schema versions this build was generated against.
 *
 * Exposed because a bot that hits a method Telegram added after this build was
 * cut needs to know which version it is talking to, and `call()` is how it
 * reaches the method meanwhile.
 */
export const schemaInfo = {
  /** Telegram Bot API version the generated surface was emitted from. */
  botApi: BOT_API_VERSION,
  /** Telegram TL schema layer the generated MTProto surface was emitted from. */
  tlLayer: TL_LAYER,
} as const
