// SPDX-License-Identifier: MPL-2.0

/**
 * Reading published server keys from PEM text.
 *
 * Keys are generated by the platform and written out by it in both PEM forms,
 * so what is read is checked against what the platform says the modulus and
 * exponent are — through its own JWK export, which shares nothing with the
 * reader under test.
 */

import { createHash, generateKeyPairSync } from 'node:crypto'
import { ValidationError } from '@yuigram/core'
import { describe, expect, it } from 'vitest'
import { rsaKeyFingerprint } from '../src/auth/keys.js'
import { serverKeysFromPem } from '../src/auth/pem.js'

const fromBase64Url = (text: string): bigint =>
  BigInt(`0x${Buffer.from(text, 'base64url').toString('hex')}`)

function rsa(bits = 2048) {
  const { publicKey } = generateKeyPairSync('rsa', { modulusLength: bits })
  const jwk = publicKey.export({ format: 'jwk' }) as { n: string; e: string }
  return {
    pkcs1: publicKey.export({ type: 'pkcs1', format: 'pem' }) as string,
    spki: publicKey.export({ type: 'spki', format: 'pem' }) as string,
    n: fromBase64Url(jwk.n),
    e: fromBase64Url(jwk.e),
  }
}

describe('reading keys', () => {
  it('reads both PEM forms to the modulus and exponent the platform reports', () => {
    const key = rsa()

    for (const text of [key.pkcs1, key.spki]) {
      const [read] = serverKeysFromPem(text)
      expect(read?.n).toBe(key.n)
      expect(read?.e).toBe(key.e)
      expect(read?.fingerprint).toBe(rsaKeyFingerprint({ n: key.n, e: key.e }))
    }
  })

  it('reads every key in a text, ignoring what is around them', () => {
    const one = rsa()
    const two = rsa()
    const text = `# datacenter keys\n${one.pkcs1}\nsome note\n${two.spki}\n`

    expect(serverKeysFromPem(text).map((key) => key.n)).toEqual([one.n, two.n])
  })
})

/**
 * Telegram's two server keys, as its own library carries them: TDLib,
 * `td/telegram/net/PublicRsaKeySharedMain.cpp` at revision 4d06d1ba3a19, where
 * the key under `is_test` is the test environment's and the other the
 * production key. Telegram's worked example of creating an authorization key
 * chooses the production key by the same fingerprint, written in wire order
 * (https://core.telegram.org/mtproto/samples-auth_key: `85FD64DE851D9DD0`).
 *
 * They are public, and they are here as a known answer. A generated key checks
 * the reader against itself; these check it against what a datacenter offers.
 */
const TELEGRAM_PRODUCTION = `-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA6LszBcC1LGzyr992NzE0ieY+BSaOW622Aa9Bd4ZHLl+TuFQ4lo4g
5nKaMBwK/BIb9xUfg0Q29/2mgIR6Zr9krM7HjuIcCzFvDtr+L0GQjae9H0pRB2OO
62cECs5HKhT5DZ98K33vmWiLowc621dQuwKWSQKjWf50XYFw42h21P2KXUGyp2y/
+aEyZ+uVgLLQbRA1dEjSDZ2iGRy12Mk5gpYc397aYp438fsJoHIgJ2lgMv5h7WY9
t6N/byY9Nw9p21Og3AoXSL2q/2IJ1WRUhebgAdGVMlV1fkuOQoEzR7EdpqtQD9Cs
5+bfo3Nhmcyvk5ftB0WkJ9z6bNZ7yxrP8wIDAQAB
-----END RSA PUBLIC KEY-----`
const TELEGRAM_TEST = `-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAyMEdY1aR+sCR3ZSJrtztKTKqigvO/vBfqACJLZtS7QMgCGXJ6XIR
yy7mx66W0/sOFa7/1mAZtEoIokDP3ShoqF4fVNb6XeqgQfaUHd8wJpDWHcR2OFwv
plUUI1PLTktZ9uW2WE23b+ixNwJjJGwBDJPQEQFBE+vfmH0JP503wr5INS1poWg/
j25sIWeYPHYeOrFp/eXaqhISP6G+q2IeTaWTXpwZj4LzXq5YOpk4bYEQ6mvRq7D1
aHWfYmlEGepfaYR8Q0YqvvhYtMte3ITnuSJs171+GDqpdKcSwHnd6FudwGO4pcCO
j4WcDuXc2CTHgH8gFTNhp/Y8/SpDOhvn9QIDAQAB
-----END RSA PUBLIC KEY-----`

describe('the fingerprint a datacenter names a key by', () => {
  const named = (pem: string): string | undefined => {
    const [key] = serverKeysFromPem(pem)

    return key === undefined ? undefined : BigInt.asUintN(64, key.fingerprint).toString(16)
  }

  it('is the one Telegram’s own clients compute for its published keys', () => {
    // SHA-1 over the modulus and the exponent as TL byte strings, each number
    // written as its own bytes with no sign byte — TDLib's `RSA::get_fingerprint`,
    // which takes them from `BN_bn2bin`.
    expect(named(TELEGRAM_PRODUCTION)).toBe('d09d1d85de64fd85')
    expect(named(TELEGRAM_TEST)).toBe('b25898df208d2603')
  })

  it('is, on the wire, the fingerprint Telegram’s worked example chooses', () => {
    // An answer from outside this repository and outside TDLib: the
    // documentation's sample exchange, which writes the eight bytes as sent.
    const [key] = serverKeysFromPem(TELEGRAM_PRODUCTION)
    const wire = Buffer.alloc(8)
    wire.writeBigInt64LE(key?.fingerprint ?? 0n)

    expect(wire.toString('hex').toUpperCase()).toBe('85FD64DE851D9DD0')
  })

  it('hashes a modulus as its own 256 bytes, without the zero DER writes before it', () => {
    const [key] = serverKeysFromPem(TELEGRAM_PRODUCTION)
    const { n, e } = key ?? { n: 0n, e: 0n }

    // The top bit is set, which is what makes DER add the byte.
    expect(n >> 2047n).toBe(1n)
    // The same key with that byte hashed in is the name no datacenter uses.
    const withSignByte = createHash('sha1')
      .update(Buffer.from(`fe01010000${n.toString(16)}000000`, 'hex'))
      .update(Buffer.from(`03${e.toString(16).padStart(6, '0')}`, 'hex'))
      .digest()
    expect(key?.fingerprint).not.toBe(withSignByte.readBigInt64LE(12))
    expect(BigInt.asUintN(64, withSignByte.readBigInt64LE(12)).toString(16)).toBe(
      '96c24024d17c6d33',
    )
  })
})

describe('refusing what is not a server key', () => {
  it('refuses a text with no key, a key of another algorithm, and a key too short', () => {
    const { publicKey: ec } = generateKeyPairSync('ec', { namedCurve: 'P-256' })

    expect(() => serverKeysFromPem('nothing here')).toThrow(ValidationError)
    expect(() => serverKeysFromPem(ec.export({ type: 'spki', format: 'pem' }) as string)).toThrow(
      /not an RSA key/,
    )
    expect(() => serverKeysFromPem(rsa(512).pkcs1)).toThrow(/shorter than any key/)
  })

  it('refuses a key cut short', () => {
    const { pkcs1 } = rsa()
    const body = pkcs1.split('\n').slice(1, -2).join('')
    const cut = `-----BEGIN RSA PUBLIC KEY-----\n${body.slice(0, 100)}\n-----END RSA PUBLIC KEY-----`

    expect(() => serverKeysFromPem(cut)).toThrow(ValidationError)
  })
})
