/**
 * Reading published server keys from PEM text.
 *
 * Keys are generated by the platform and written out by it in both PEM forms,
 * so what is read is checked against what the platform says the modulus and
 * exponent are — through its own JWK export, which shares nothing with the
 * reader under test.
 */

import { generateKeyPairSync } from 'node:crypto'
import { ValidationError } from '@yuigram/core'
import { describe, expect, it } from 'vitest'
import { rsaKeyFingerprint } from '../src/auth/keys.js'
import { serverKeysFromPem } from '../src/auth/pem.js'

const fromBase64Url = (text: string): bigint =>
  BigInt(`0x${Buffer.from(text, 'base64url').toString('hex')}`)

function rsa(bits = 2048) {
  const { publicKey } = generateKeyPairSync('rsa', { modulusLength: bits })
  const jwk = publicKey.export({ format: 'jwk' }) as { n: string; e: string }
  return {
    pkcs1: publicKey.export({ type: 'pkcs1', format: 'pem' }) as string,
    spki: publicKey.export({ type: 'spki', format: 'pem' }) as string,
    n: fromBase64Url(jwk.n),
    e: fromBase64Url(jwk.e),
  }
}

describe('reading keys', () => {
  it('reads both PEM forms to the modulus and exponent the platform reports', () => {
    const key = rsa()

    for (const text of [key.pkcs1, key.spki]) {
      const [read] = serverKeysFromPem(text)
      expect(read?.n).toBe(key.n)
      expect(read?.e).toBe(key.e)
      expect(read?.fingerprint).toBe(rsaKeyFingerprint({ n: key.n, e: key.e }))
    }
  })

  it('reads every key in a text, ignoring what is around them', () => {
    const one = rsa()
    const two = rsa()
    const text = `# datacenter keys\n${one.pkcs1}\nsome note\n${two.spki}\n`

    expect(serverKeysFromPem(text).map((key) => key.n)).toEqual([one.n, two.n])
  })
})

describe('refusing what is not a server key', () => {
  it('refuses a text with no key, a key of another algorithm, and a key too short', () => {
    const { publicKey: ec } = generateKeyPairSync('ec', { namedCurve: 'P-256' })

    expect(() => serverKeysFromPem('nothing here')).toThrow(ValidationError)
    expect(() => serverKeysFromPem(ec.export({ type: 'spki', format: 'pem' }) as string)).toThrow(
      /not an RSA key/,
    )
    expect(() => serverKeysFromPem(rsa(512).pkcs1)).toThrow(/shorter than any key/)
  })

  it('refuses a key cut short', () => {
    const { pkcs1 } = rsa()
    const body = pkcs1.split('\n').slice(1, -2).join('')
    const cut = `-----BEGIN RSA PUBLIC KEY-----\n${body.slice(0, 100)}\n-----END RSA PUBLIC KEY-----`

    expect(() => serverKeysFromPem(cut)).toThrow(ValidationError)
  })
})
